// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOOi75gYOEgVOADNUk-x__fcv2hqc-5g',
    appId: '1:885794178084:web:0efe466296263380dac4b1',
    messagingSenderId: '885794178084',
    projectId: 'proyecto-final-d3082',
    authDomain: 'proyecto-final-d3082.firebaseapp.com',
    storageBucket: 'proyecto-final-d3082.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0EmA35dcSJ8TQtxK_ApWJ1PULTtfpgKk',
    appId: '1:885794178084:android:8522595efdbeedecdac4b1',
    messagingSenderId: '885794178084',
    projectId: 'proyecto-final-d3082',
    storageBucket: 'proyecto-final-d3082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0U74G9rxlDJ1nz0Mc8i91GNx1QFVFhE0',
    appId: '1:885794178084:ios:48526496d21e7891dac4b1',
    messagingSenderId: '885794178084',
    projectId: 'proyecto-final-d3082',
    storageBucket: 'proyecto-final-d3082.firebasestorage.app',
    iosBundleId: 'com.Proyecto2.app',
  );
}
